default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  username: root
  password: password
  host: db
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
